name: Coletor de Seguidores Diário

on:
schedule:
  - cron: '0 5 * * *'  # Executa todos os dias às 5:00 UTC
workflow_dispatch:  # Permite execução manual

jobs:
scrape:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Instalar dependências
      run: |
        pip install selenium webdriver-manager pandas openpyxl
        
    - name: Executar script de coleta
      run: python scraper.py
      
    - name: Configurar Git para commit
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
    - name: Commit e push dos novos dados
      run: |
        git add resultados.xlsx
        git commit -m "Atualização diária de dados [$(date)]" || echo "Sem alterações para commit"
        git push