name: Coletor de Seguidores Diário
on:
  schedule:
    - cron: '0 12 * * *'  # Executa todos os dias às 5:00 UTC
  workflow_dispatch:  # Permite execução manual

# Definir permissões necessárias para commits
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Instalar dependências
        run: |
          pip install selenium webdriver-manager pandas openpyxl pyyaml
          
      - name: Verificar ambiente
        run: |
          echo "Diretório atual: $(pwd)"
          echo "Conteúdo do diretório: $(ls -la)"
          echo "Versão do Chrome: $(chrome --version)"
          
      - name: Executar script de coleta
        run: |
          python scraper.py
          
      - name: Configurar Git para commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
      - name: Commit e push dos novos dados
        run: |
          # Adicionar todos os arquivos de resultados
          git add resultados.xlsx
          git add resultados.csv
          git add relatorio.md || true
          git commit -m "Atualização diária de dados [$(date)]" || echo "Sem alterações para commit"
          git push
